import os
import sys

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    print("Pillow not installed. Run: pip install Pillow")
    sys.exit(1)

# List of CMC-7 characters
# Using standard ascii for digits. For symbols, we use arbitrary letters
# A, B, C, D, E just to draw *something* distinct if we don't have a CMC7 font.
CHARS = [
    ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'),
    ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'),
    ('\u2446', 'A'), ('\u2447', 'B'), ('\u2448', 'C'), ('\u2449', 'D'), ('\u244A', 'E')
]

WIDTH = 32
HEIGHT = 64

OUT_DIR = os.path.join(os.path.dirname(__file__), 'templates-preview')
TS_FILE = os.path.join(os.path.dirname(__file__), '..', 'src', 'ocr', 'templates', 'index.ts')

os.makedirs(OUT_DIR, exist_ok=True)

try:
    font = ImageFont.truetype("arial.ttf", 40)
except IOError:
    font = ImageFont.load_default(size=40)

templates_data = {}

for unicode_char, display_char in CHARS:
    # 1. Create a white background image
    img = Image.new('L', (WIDTH, HEIGHT), color=255)
    draw = ImageDraw.Draw(img)
    
    # 2. Draw the character in black (color 0)
    # Center text
    bbox = draw.textbbox((0, 0), display_char, font=font)
    w = bbox[2] - bbox[0]
    h = bbox[3] - bbox[1]
    
    x = (WIDTH - w) / 2
    y = (HEIGHT - h) / 2 - bbox[1]
    
    draw.text((x, y), display_char, font=font, fill=0)
    
    # 3. Save preview (for visual verification)
    safe_name = display_char if unicode_char.isdigit() else f"SYM_{display_char}"
    img.save(os.path.join(OUT_DIR, f"{safe_name}.png"))
    
    # 4. Extract pixel data to binary array (1 for black/foreground, 0 for white/background)
    # OCR usually operates on 0-255 where 255 is white.
    # The requirement might just be 8-bit grayscale for the template matching (T-013).
    # We will export the raw 8-bit grayscale values.
    pixel_data = list(img.getdata())
    templates_data[unicode_char] = pixel_data

# Write the TypeScript file
ts_content = [
    "// AUTO-GENERATED FILE. DO NOT EDIT.",
    "// Generated by tools/generate-templates.py",
    "",
    "export type CMC7Char = " + " | ".join(f"'{c[0]}'" for c in CHARS) + ";",
    "",
    "export const TEMPLATES: Record<CMC7Char, Uint8Array> = {"
]

for unicode_char, _ in CHARS:
    data = templates_data[unicode_char]
    data_str = ",".join(map(str, data))
    # Unicode key format
    key = f"'{unicode_char}'"
    ts_content.append(f"  {key}: new Uint8Array([{data_str}]),")

ts_content.append("};")
ts_content.append("")

with open(TS_FILE, 'w', encoding='utf-8') as f:
    f.write("\n".join(ts_content))

print(f"Generated {len(CHARS)} templates.")
print(f"Previews saved to {OUT_DIR}")
print(f"TypeScript index saved to {TS_FILE}")
